name: vad_plus
description: "Silero VAD ONNX voice activity detection FFI plugin for Flutter."
version: 0.1.0

homepage: https://github.com/Miracle-Blue/vad_plus
repository: https://github.com/Miracle-Blue/vad_plus
issue_tracker: https://github.com/Miracle-Blue/vad_plus/issues

platforms:
  android:
  ios:
  macos:

environment:
  sdk: ^3.9.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.5
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
